# Generated by Django 3.0.4 on 2020-03-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_api', '0002_auto_20200320_0555'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='role',
            table='employee_role',
        ),
        migrations.AlterModelTable(
            name='salary',
            table='employee_salary',
        ),
    ]
